server:
  # ??????
  port: 8080
  servlet:
    # ???????
    context-path: /share-app-api

spring:
  application:
    # ????
    name: share-app-api
  profiles:
    # ????
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

# ?????????
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # ????????????
  type-aliases-package: top.hyzhu.*.entity
  configuration:
    # ???????
    map-underscore-to-camel-case: true
    cache-enabled: false
    # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ??????
      logic-delete-field: true
      logic-delete-value: 1
      logic-not-delete-value: 0

# ????????
logging:
  # ??????
  config: classpath:log/logback-spring.xml


# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # ?? controller ?????????
      packages-to-scan: top.hyzhu.share.app.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456

# ??????????? url ????????
auth:
  valid_urls:
    - /auth/logout
    - /user/**
    - /resource/publish

# ??? OSS ????????
aliyun:
  oss:
    # oss对外访服务的访问域名，按照自己情况修改
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 访问身份验证中用到用户标识，替换成自己的
    accessKeyId: LTAI5tFGTwz3KAkmNkHXtv3j
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥，替换成自己的
    accessKeySecret: 7phmgsE5reCpGvoIrzCEth1PphVpmW
    # oss 的存储空间名
    bucketName: hyzhu-oss

# ??????????????
share:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018ef194263a66df
      accountToken: 84ae894abd6d401f8f2f6f1b7613e6bf
      appId: 2c94811c8cd4da0a018ef19427c366e6
      templateId: 1